name: Android build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update in progress
        run: echo "V0.2 source upload in progress"
